### ISSUE TITLE
Impossible dependency resolution

### ISSUE THREAD

**Issue by miguelcorrea** [patrickbryant1/Cfold#1]
Hi Patrick,

I'm trying to install the dependencies required to run Cfold in a fresh new conda environment (with python 3.10) and it seems that there are some conflicts between the versions specified in the README. Could you have a look?

ERROR: Cannot install biopython==1.81, chex==0.1.5, dm-haiku==0.0.9, jax==0.3.24, numpy==1.21.6, pandas==1.3.5, scipy==1.7.3 and tensorflow-cpu==2.12.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.21.6
    jax 0.3.24 depends on numpy>=1.20
    dm-haiku 0.0.9 depends on numpy>=1.18.0
    pandas 1.3.5 depends on numpy>=1.21.0; python_version >= "3.10"
    biopython 1.81 depends on numpy
    chex 0.1.5 depends on numpy>=1.18.0
    scipy 1.7.3 depends on numpy<1.23.0 and >=1.16.5
    tensorflow-cpu 2.12.0 depends on numpy<1.24 and >=1.22

**Comment by patrickbryant1** [comment]
Hi,

This are the exact packages I have installed.
The conflict error you get is strange. If you look at it you will see e.g. that
"The user requested numpy==1.21.6
jax 0.3.24 depends on numpy>=1.20"
This is not an error. 

The only conflict I can see is with "tensorflow-cpu 2.12.0 depends on numpy<1.24 and >=1.22"

Try not installing tensorflow-cpu 2.12.0 since regular tensorflow should be enough:

pip install -U jaxlib==0.3.24+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install jax==0.3.24
pip install ml-collections==0.1.1
pip install dm-haiku==0.0.9
pip install pandas==1.3.5
pip install biopython==1.81
pip install chex==0.1.5
pip install dm-tree==0.1.8
pip install immutabledict==2.0.0
pip install numpy==1.21.6
pip install scipy==1.7.3
pip install tensorflow==2.11.0
pip install optax==0.1.4

Let me know if this helps.

**Comment by miguelcorrea** [comment]
Hi,

I think the weirdness of the message simply comes from conda trying to exhaustively point out all possible issues.

It seems indeed tensorflow-cpu was unnecessary after all - Cfold is now happily producing predictions. Thanks!
